- hosts: all
  connection: local
  gather_facts: yes
  become: no
  tasks:
    - name: Check the war file exists
      stat:
        path: /opt/jenkins-tomcat.war
      register: war_file

    - debug:
        msg: "File exists..."
      when: war_file.stat.exists
    - debug:
        msg: "File not found"
      when:  not war_file.stat.exists
    - name: Download War file
      get_url:
        force: yes
        url: http://192.168.0.143:8081/artifactory/libs-release-local/jenkins-tomcat.war
        dest: /opt/jenkins-tomcat.war
        mode: 0755
      #shell: creates=/tmp/tomcat/jenkins-tomcat.war chdir=/tmp/tomcat http://192.168.0.143:8081/artifactory/libs-release-local/jenkins-tomcat.war
      when: not war_file.stat.exists 
        
