- hosts: all
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Check the war file exists
      stat:
        path: /opt/jenkins-tomcat.war
      register: war_file

    - debug:
        msg: "File exists..."
      when: war_file.stat.exists
    - debug:
        msg: "File not found"
      when:  not war_file.stat.exists
    - name: Download War file
      get_url:
        url: http://192.168.0.143:8081/artifactory/libs-release-local/jenkins-tomcat.war
        dest: /opt/
        username: admin
        password: Rajchinna
      when:  not war_file.stat.exists 
        
