- hosts: all
  connection: local
  gather_facts: yes
  become: no
  tasks:
    - name: Check the war file exists
      stat:
        path: /tmp/jenkins-tomcat.war
      register: war_file

    - debug:
        msg: "File exists..."
      when: war_file.stat.exists
    - debug:
        msg: "File not found"
      when:  not war_file.stat.exists
    - name: Download War file
      synchronize: src="http://192.168.0.143:8081/artifactory/libs-release-local/jenkins-tomcat.war" dest="/tmp"
      when: not war_file.stat.exists 
        
